name: feature
description: "For PR's that add new features or functionality"
title: "[FEATURE] Title"
labels: enhancement
assignees:
  - tycrek
projects: 1
body:
  - type: markdown
    value: "## Thank you for contributing to ass!"
  - type: markdown
    value: "Please fill out this form to the best of your ability"
  - type: checkboxes
    attributes:
      label: Checklist
      id: checklist
      options:
        - label: "I have read the Contributing Guidelines (coming soon)"
        - label: "I acknowledge that any submitted code will be licensed under the [ISC License](https://github.com/tycrek/ass/blob/master/LICENSE)"
          required: true
  - type: input
    label: Relevant Issue
    id: issue
    description: "Issue this PR resolves, if applicable"
    placeholder: "#123"
  - type: textarea
    label: Description
    description: "Describe your PR in detail"
    id: description
    validations:
      required: true
  
